### ISSUE TITLE
"Neuester Beitrag von :" name missing

### ISSUE THREAD

**Issue by tobru** [opensource-challenge/opensource-challenge-client#21] opened 2016-12-03 17:38 UTC
Somehow the name is missing in the title block "Neuester Beitrag von :". It just displays the title of the contribution, but not the name of the contributor.

**Comment by lbischof** [comment] 2016-12-03 18:12
It seems to fail when getting the nested (belongsTo) user model. The name appears after visiting a "day" and going back... I found this while googling: http://stackoverflow.com/questions/14521182/ember-data-does-not-support-embedded-objects I can't reproduce this issue locally.

**Comment by topaxi** [comment] 2016-12-04 12:43
The API was returning `http://` links while we're running on `https`.

Fixed with:
https://github.com/opensource-challenge/opensource-challenge-api/commit/e7bbc31b9612ff94d4088395e83e6737609acc2b
https://github.com/opensource-challenge/opensource-challenge-api/commit/cfaf61d240802b069037fad3f6ea9961815b9860
https://github.com/opensource-challenge/opensource-challenge-api/commit/c1d69cf27795356052b7b1d2196032ce995ea6e9

**Closed by topaxi** 2016-12-04 12:43 UTC
